lib/timesheets_web/router.ex
defmodule TimesheetsWeb.Router do
  use TimesheetsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug TimesheetsWeb.Plugs.FetchCurrentUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetsWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/sheets",SheetController,
       only: [:new, :create, :index, :show, :update, :edit]   

    resources "/tasks", TaskController,
	    only: [:new, :create]
      
    resources "/users", UserController,
      only: [:new, :create, :show, :index]
      
    resources "/sessions", SessionController, 
      only: [:new, :create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetsWeb do
  #   pipe_through :api
  # end
end

lib/timesheets_web/controllers/session_controller.ex
defmodule TimesheetsWeb.SessionController do
  use TimesheetsWeb, :controller

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"email" => email, "password" => password}) do
    user = Timesheets.Users.authenticate(email, password)
    if user do
      conn
      |> put_session(:user_id, user.id)
      |> put_flash(:info, "Welcome back #{user.email}")
      |> redirect(to: Routes.sheet_path(conn, :index))
    else
      conn
      |> put_flash(:error, "Login failed.")
      |> redirect(to: Routes.page_path(conn, :index))
    end
  end

  def delete(conn, _params) do
    conn
    |> delete_session(:user_id)
    |> put_flash(:info, "Logged out.")
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/timesheets_web/views/session_view.ex
defmodule TimesheetsWeb.SessionView do
  use TimesheetsWeb, :view
end

lib/timesheets_web/templates/session/new.html.eex
<%= form_for @conn, Routes.session_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= label f, :email %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

   <div class="form-group">
    <%= label f, :password %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div>
    <%= submit "Log In", class: "btn btn-primary" %>
  </div>
<% end %>